/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_ROSEN_SESSION_IPC_INTERFACE_CODE_H
#define OHOS_ROSEN_SESSION_IPC_INTERFACE_CODE_H

namespace OHOS {
namespace Rosen {
enum class SessionInterfaceCode {
    // Base
    TRANS_ID_CONNECT = 0,
    TRANS_ID_FOREGROUND,
    TRANS_ID_BACKGROUND,
    TRANS_ID_DISCONNECT,
    TRANS_ID_SHOW,
    TRANS_ID_HIDE,
    TRANS_ID_CHANGE_SESSION_VISIBILITY_WITH_STATUS_BAR,
    TRANS_ID_ACTIVE_PENDING_SESSION,
    TRANS_ID_TERMINATE,
    TRANS_ID_EXCEPTION,
    TRANS_ID_DRAWING_COMPLETED,
    TRANS_ID_APP_REMOVE_STARTING_WINDOW,
    TRANS_ID_BATCH_ACTIVE_PENDING_SESSION,
    TRANS_ID_RESTART_APP,

    // Scene
    TRANS_ID_SESSION_EVENT = 100,
    TRANS_ID_UPDATE_SESSION_RECT,
    TRANS_ID_RAISE_TO_APP_TOP,
    TRANS_ID_BACKPRESSED,
    TRANS_ID_MARK_PROCESSED,
    TRANS_ID_SET_MAXIMIZE_MODE,
    TRANS_ID_GET_MAXIMIZE_MODE,
    TRANS_ID_NEED_AVOID,
    TRANS_ID_GET_AVOID_AREA,
    TRANS_ID_GET_AVOID_AREA_IGNORING_VISIBILITY,
    TRANS_ID_SET_ASPECT_RATIO,
    TRANS_ID_SET_CONTENT_ASPECT_RATIO,
    TRANS_ID_UPDATE_WINDOW_ANIMATION_FLAG,
    TRANS_ID_UPDATE_CUSTOM_ANIMATION,
    TRANS_ID_RAISE_ABOVE_TARGET,
    TRANS_ID_RAISE_MAIN_WINDOW_ABOVE_TARGET,
    TRANS_ID_RAISE_APP_MAIN_WINDOW,
    TRANS_ID_PROCESS_POINT_DOWN_SESSION,
    TRANS_ID_SEND_POINTEREVENT_FOR_MOVE_DRAG,
    TRANS_ID_SET_LANDSCAPE_MULTI_WINDOW,
    TRANS_ID_GET_IS_MID_SCENE,
    TRANS_ID_UPDATE_RECTCHANGE_LISTENER_REGISTERED,
    TRANS_ID_SET_CALLING_SESSION_ID,
    TRANS_ID_SET_CUSTOM_DECOR_HEIGHT,
    TRANS_ID_SET_DECOR_VISIBLE,
    TRANS_ID_UPDATE_SESSION_PROPERTY,
    TRANS_ID_ADJUST_KEYBOARD_LAYOUT,
    TRANS_ID_LAYOUT_FULL_SCREEN_CHANGE,
    TRANS_ID_DEFAULT_DENSITY_ENABLED,
    TRANS_ID_UPDATE_COLOR_MODE,
    TRANS_ID_GET_FORCE_LANDSCAPE_CONFIG,
    TRANS_ID_GET_HOOK_WINDOW_INFO,
    TRANS_ID_GET_STATUSBAR_HEIGHT,
    TRANS_ID_SET_DIALOG_SESSION_BACKGESTURE_ENABLE,
    TRANS_ID_FRAME_LAYOUT_FINISH,
    TRANS_ID_SET_SYSTEM_DRAG_ENABLE,
    TRANS_ID_SYNC_SESSION_EVENT,
    TRANS_ID_REQUEST_FOCUS,
    TRANS_ID_IS_START_MOVING,
    TRANS_ID_GET_ALL_AVOID_AREAS,
    TRANS_ID_GET_TARGET_ORIENTATION_CONFIG_INFO,
    TRANS_ID_CONVERT_ORIENTATION_AND_ROTATION,
    TRANS_ID_UPDATE_CLIENT_RECT,
    TRANS_ID_TITLE_AND_DOCK_HOVER_SHOW_CHANGE,
    TRANS_ID_RESTORE_MAIN_WINDOW,
    TRANS_ID_SET_GESTURE_BACK_ENABLE,
    TRANS_ID_SUB_MODAL_TYPE_CHANGE,
    TRANS_ID_MAIN_MODAL_TYPE_CHANGE,
    TRANS_ID_GET_GLOBAL_SCALED_RECT,
    TRANS_ID_SET_WINDOW_RECT_AUTO_SAVE,
    TRANS_ID_SET_SUPPORT_WINDOW_MODES,
    TRANS_ID_SET_SESSION_LABEL_AND_ICON,
    TRANS_ID_SET_WINDOW_CORNER_RADIUS,
    TRANS_ID_START_MOVING_WITH_COORDINATE,
    TRANS_ID_GET_CROSS_AXIS_STATE,
    TRANS_ID_CONTAINER_MODAL_EVENT,
    TRANS_ID_SET_FOLLOW_PARENT_MULTI_SCREEN_POLICY,
    TRANS_ID_SET_FOLLOW_PARENT_LAYOUT_ENABLED,
    TRANS_ID_UPDATE_ROTATION_CHANGE,
    TRANS_ID_UPDATE_SCREEN_SHOT_APP_EVENT_REGISTERED,
    TRANS_ID_UPDATE_ACROSS_DISPLAYS_REGISTERED,
    TRANS_ID_UPDATE_FLAG,
    TRANS_ID_GET_IS_HIGHLIGHTED,
    TRANS_ID_NOTIFY_DISABLE_DELEGATOR_CHANGE,
    TRANS_ID_SET_WINDOW_ANCHOR_INFO,
    TRANS_ID_SET_WINDOW_SHADOWS,

    // keyboard
    TRANS_ID_CHANGE_KEYBOARD_VIEW_MODE,
    TRANS_ID_SET_KEYBOARD_DID_SHOW_REGISTERED,
    TRANS_ID_SET_KEYBOARD_DID_HIDE_REGISTERED,
    TRANS_ID_SET_KEYBOARD_WILL_SHOW_REGISTERED,
    TRANS_ID_SET_KEYBOARD_WILL_HIDE_REGISTERED,

    // Window Transition Animation For PC
    TRANS_ID_SET_WINDOW_TRANSITION_ANIMATION,

    // Window Layout Global Coordinate System
    TRANS_ID_UPDATE_GLOBAL_DISPLAY_RECT,

    // Extension
    TRANS_ID_TRANSFER_ABILITY_RESULT = 500,
    TRANS_ID_TRANSFER_EXTENSION_DATA = 501,
    TRANS_ID_NOTIFY_EXTENSION_DIED,
    TRANS_ID_NOTIFY_ASYNC_ON,
    TRANS_ID_NOTIFY_SYNC_ON,
    TRANS_ID_NOTIFY_REPORT_ACCESSIBILITY_EVENT,
    TRANS_ID_TRIGGER_BIND_MODAL_UI_EXTENSION,
    TRANS_ID_NOTIFY_EXTENSION_TIMEOUT,
    TRANS_ID_NOTIFY_EXTENSION_EVENT_ASYNC,
    TRANS_ID_NOTIFY_EXTENSION_DETACH_TO_DISPLAY,
    TRANS_ID_SEND_EXTENSION_DATA,

    // Window Event
    TRANS_ID_SEND_COMMAND_EVENT,

    // KeyFrame
    TRANS_ID_KEY_FRAME_ANIMATE_END,
    TRANS_ID_UPDATE_KEY_FRAME_CLONE_NODE,
    TRANS_ID_SET_DRAG_KEY_FRAME_POLICY,

    // PC Fold Screen
    TRANS_ID_GET_WATERFALL_MODE,
    TRANS_ID_MAIN_WINDOW_FULL_SCREEN_ACROSS_DISPLAYS,
    TRANS_ID_USE_IMPLICT_ANIMATION,

    // PictureInPicture
    TRANS_ID_NOTIFY_PIP_WINDOW_PREPARE_CLOSE = 800,
    TRANS_ID_UPDATE_PIP_RECT,
    TRANS_ID_UPDATE_PIP_CONTROL_STATUS,
    TRANS_ID_UPDATE_PIP_TEMPLATE_INFO,
    TRANS_ID_SET_AUTOSTART_PIP,
    TRANS_ID_SET_PIP_PARENT_WINDOWID,

    // Window Pattern
    TRANS_ID_NOTIFY_SNAPSHOT_UPDATE,
    TRANS_ID_NOTIFY_WINDOW_ATTACH_STATE_LISTENER_REGISTERED,
    TRANS_ID_SET_START_WINDOW_BACKGROUND_COLOR,
    TRANS_IS_SET_IMAGE_FOR_RECENT,
    TRANS_ID_NOTIFY_WINDOW_ATTACH_STATE_CHANGE,

    // Window source
    TRANS_ID_SET_SUBWINDOW_SOURCE,

    // window animation
    TRANS_ID_SET_FRAMERECT_FOR_PARTIAL_ZOOMIN,

    // Floating Ball
    TRANS_ID_UPDATE_FLOATING_BALL,
    TRANS_ID_NOTIFY_FLOATING_BALL_PREPARE_CLOSE,
    TRANS_ID_START_FLOATING_BALL_MAIN_WINDOW,
    TRANS_ID_GET_FLOATING_BALL_WINDOW_ID,

    // Compatible Mode
    TRANS_ID_NOTIFY_IS_FULL_SCREEN_IN_FORCE_SPLIT,
};
} // namespace Rosen
} // namespace OHOS

#endif  // OHOS_ROSEN_SESSION_IPC_INTERFACE_CODE_H
