/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SESSION_STAGE_IPC_INTERFACE_CODE_H
#define SESSION_STAGE_IPC_INTERFACE_CODE_H

/* SAID: 4606 */
namespace OHOS {
namespace Rosen {
enum class SessionStageInterfaceCode {
    TRANS_ID_SET_ACTIVE = 0,
    TRANS_ID_NOTIFY_SIZE_CHANGE,
    TRANS_ID_HANDLE_BACK_EVENT,
    TRANS_ID_NOTIFY_FOCUS_CHANGE,
    TRANS_ID_NOTIFY_DESTROY,
    TRANS_ID_NOTIFY_TRANSFER_COMPONENT_DATA,
    TRANS_ID_NOTIFY_OCCUPIED_AREA_CHANGE_INFO,
    TRANS_ID_UPDATE_AVOID_AREA,
    TRANS_ID_NOTIFY_SCREEN_SHOT,
    TRANS_ID_NOTIFY_SCREEN_SHOT_APP_EVENT,
    TRANS_ID_DUMP_SESSSION_ELEMENT_INFO,
    TRANS_ID_NOTIFY_TOUCH_OUTSIDE,
    TRANS_ID_NOTIFY_SECURE_LIMIT_CHANGE,
    TRANS_ID_NOTIFY_WINDOW_MODE_CHANGE,
    TRANS_ID_GET_TOP_NAV_DEST_NAME,
    TRANS_ID_NOTIFY_LAYOUT_FINISH_AFTER_WINDOW_MODE_CHANGE,
    TRANS_ID_NOTIFY_DENSITY_CHANGE,
    TRANS_ID_NOTIFY_ORIENTATION_CHANGE,
    TRANS_ID_UPDATE_SESSION_VIEWPORT_CONFIG,
    TRANS_ID_NOTIFY_FOREGROUND_INTERACTIVE_STATUS,
    TRANS_ID_NOTIFY_CONFIGURATION_UPDATED,
    TRANS_ID_NOTIFY_MAXIMIZE_MODE_CHANGE,
    TRANS_ID_NOTIFY_TRANSFER_COMPONENT_DATA_SYNC,
    TRANS_ID_NOTIFY_CLOSE_EXIST_PIP_WINDOW,
    TRANS_ID_NOTIFY_SESSION_FOREGROUND,
    TRANS_ID_NOTIFY_SESSION_BACKGROUND,
    TRANS_ID_NOTIFY_TITLE_POSITION_CHANGE,
    TRANS_ID_NOTIFY_WINDOW_VISIBILITY_CHANGE,
    TRANS_ID_NOTIFY_WINDOW_OCCLUSION_STATE,
    TRANS_ID_NOTIFY_TRANSFORM_CHANGE,
    TRANS_ID_NOTIFY_DIALOG_STATE_CHANGE,
    TRANS_ID_NOTIFY_DISPLAYID_CHANGE,
    TRANS_ID_SET_PIP_ACTION_EVENT,
    TRANS_ID_SET_PIP_CONTROL_EVENT,
    TRANS_ID_NOTIFY_DISPLAY_MOVE,
    TRANS_ID_NOTIFY_SWITCH_FREEMULTIWINDOW,
    TRANS_ID_GET_UI_CONTENT_REMOTE_OBJ,
    TRANS_ID_NOTIFY_KEYBOARD_INFO_CHANGE,
    TRANS_ID_NOTIFY_DENSITY_FOLLOW_HOST,
    TRANS_ID_PCAPPINPADNORMAL_CLOSE,
    TRANS_ID_NOTIFY_DENSITY_UNIQUE,
    TRANS_ID_NOTIFY_SESSION_FULLSCREEN,
    TRANS_ID_NOTIFY_SINGLE_HAND_TRANSFORM,
    TRANS_ID_NOTIFY_KEYBOARD_ANIMATION_COMPLETED,
    TRANS_ID_NOTIFY_ROTATION_PROPERTY,
    TRANS_ID_NOTIFY_PAGE_ROTATION_ISIGNORED,
    TRANS_ID_NOTIFY_ROTATION_CHANGE,
    TRANS_ID_SET_CURRENT_ROTATION,
    TRANS_ID_NOTIFY_PAUSED_STATUS,
    TRANS_ID_NOTIFY_USE_CONTROL_STATUS,
    TRANS_ID_GET_ROUTER_STACK_INFO,
    TRANS_ID_NOTIFY_KEYBOARD_ANIMATION_WILLBEGIN,

    // Extension
    TRANS_ID_SEND_EXTENSION_DATA,
    TRANS_ID_NOTIFY_DUMP_INFO,

    TRANS_ID_LINK_KEYFRAME_NODE,
    TRANS_ID_SET_STAGE_KEYFRAME_POLICY,

    TRANS_ID_SET_SPLIT_BUTTON_VISIBLE,
    TRANS_ID_NOTIFY_COMPATIBLE_MODE_PROPERTY_CHANGE,
    TRANS_ID_SET_ENABLE_DRAG_BY_SYSTEM,
    TRANS_ID_SET_FULLSCREEN_WATERFALL_MODE,
    TRANS_ID_SET_SUPPORT_ENTER_WATERFALL_MODE,
    TRANS_ID_SEND_CONTAINER_MODAL_EVENT,
    TRANS_ID_SET_DRAG_ACTIVATED,
    TRANS_ID_NOTIFY_HIGHLIGHT_CHANGE,
    TRANS_ID_NOTIFY_CROSS_AXIS,
    TRANS_ID_NOTIFY_PIPSIZE_CHANGE,
    TRANS_ID_NOTIFY_WINDOW_ATTACH_STATE_CHANGE,
    TRANS_ID_NOTIFY_APP_FORCE_LANDSCAPE_CONFIG_UPDATED,
    TRANS_ID_NOTIFY_APP_HOOK_WINDOW_INFO_UPDATED,
    TRANS_ID_CLOSE_SPECIFIC_SCENE,
    // Layout
    TRANS_ID_UPDATE_WINDOW_MODE_FOR_UI_TEST,
    TRANS_ID_UPDATE_GLOBAL_DISPLAY_RECT,
    // Floating ball
    TRANS_ID_SEND_FB_ACTION_EVENT,
    TRANS_ID_NOTIFY_UPDATE_SHOW_DECOR_IN_FREE_MULTI_WINDOW,

    // Window Animation
    TRANS_ID_UPDATE_ANIMATION_SPEED,
    // Pip active status
    TRANS_ID_ACTIVE_STATUS_CHANGE,
};
}   // namespace Rosen
}   // namespace OHOS

#endif  // SESSION_STAGE_IPC_INTERFACE_CODE_H